site_name: ArcanNN - Training
repo_url: https://github.com/TheoreticalChemistryGroupENS/arcann_training
repo_name: TheoreticalChemistryGroupENS/arcann_training
plugins:
    - search
    - awesome-pages
    - markdownextradata
theme:
    name: material
    icon:
        repo: fontawesome/brands/github
